name: Angular Build and Deploy

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      deploy_dir: ${{ steps.set_deploy_dir.outputs.DEPLOY_DIR }}
      build_output_dir: ${{ steps.build_app.outputs.build_output_dir }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Verify Node and NPM versions
        run: |
          node -v
          npm -v

      - name: Verify Angular CLI Version
        run: ./node_modules/.bin/ng --version

      - name: Debug node_modules/.bin
        run: ls -al ./node_modules/.bin

      - name: Build Angular app (Development)
        if: github.ref != 'refs/heads/main'
        run: |
          ./node_modules/.bin/ng build --configuration=development
          echo "build_output_dir=./dist/webovky" >> $GITHUB_OUTPUT

      - name: Build Angular app (Production)
        if: github.ref == 'refs/heads/main'
        run: |
          ./node_modules/.bin/ng build --configuration=production
          echo "build_output_dir=./dist/webovky" >> $GITHUB_OUTPUT

      - name: Set deploy dir
        id: set_deploy_dir
        run: |
          echo "DEPLOY_DIR=${{ github.ref == 'refs/heads/main' && './www' || './develop/www' }}" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.CD_FTP_SERVER }}
          user: ${{ secrets.CD_FTP_USERNAME }}
          password: ${{ secrets.CD_FTP_PASSWORD }}
          local_dir: ${{ needs.build.outputs.build_output_dir }}
          remote_dir: ${{ needs.build.outputs.deploy_dir }}
          delete: "true"

      - name: Clean up
        run: rm -rf ./dist
